


version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: "sqlite:latest"
    volumes:
      - data:/var/lib/sqlite
volumes:
  data:
